[[redirects]]
  from = "/robots.txt"
  to = "https://raw.githubusercontent.com/monitorin/kitbloggerProxy/main/robots.txt"
  status = 200
  force = true
  
[[redirects]]
  from = "/*"
  to = "https://www.timnesia.com/:splat"
  status = 200
  force = true
  headers = {X-From = "netlify", X-Custom-Token = "my custom token"}
